name: build

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
